import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Services | Web Development in Turkey , Mareketing , Design ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>){
  return (
   
       <div className="flex bg-black flex-col pt-36 items-center justify-center h-full">
       {children}
       </div>
   
  );
}

